name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/login-action@v1
      with:
        login-server: registry-1.docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t codybisram/creditgroup1frontend:${{ github.sha }}
        docker push codybisram/creditgroup1frontend:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'CreditCreate1-fe-docker' 
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'codybisram/creditgroup1frontend:${{ github.sha }}'
